Compatibility with macOS
ninewise/terminal-sharing pull request #1
Opened 2020-09-22 10:26 UTC by jenspots

Before this change, running 'host' on macOS would result in a "found uuidgen: no" error. To reduce duplicate code, a for-loop was implemented.

2020-09-22 13:53 UTC, ninewise requested changes
The macOS issue was fixed by using `uuidgen` without `-V`, but I agree using `command` and a for loop are better.

Could you contract the for into `for ...; do` (and the if) to keep the style consistent?

2020-09-22 13:53 UTC, ninewise commented on host
> +	if ! command -v $COMMAND &> /dev/null
`&>` works only in bash, not all POSIX sh's. Could you replace this with `> /dev/null 2>&1` again?

2020-09-22 13:53 UTC, ninewise commented on host
> +		echo $COMMAND 'found: no'
Even though `$COMMAND` is a known string here, and thus safe, I'd prefer `printf '%s found: no\n' "$COMMAND"`.

2020-09-23 06:53 UTC, jenspots commented
Thank you for your feedback. I added the changes you requested. I also changed all the other files that checked for commands for sake of consistency.

2020-09-23 07:34 UTC, ninewise approved these changes
Cool, thanks.

2020-09-23 07:35 UTC, ninewise commented
Cool, thanks.

2020-09-23 07:35 UTC, merged